In [7]:
import numpy as np

matrix_3x3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

mean_3x3 = matrix_3x3.mean()
var_3x3 = matrix_3x3.var()
std_3x3 = matrix_3x3.std()
column_mean = matrix_3x3.mean(axis=0)

print(f"Mean: {mean_3x3}")
print(f"Variance: {var_3x3}")
print(f"Standard Deviation: {std_3x3}")
print(f"Column Mean: {column_mean}")


matrix_4x3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

reshape_2x6 = matrix_4x3.reshape(2,6)

size = reshape_2x6.size

print(f"Size: {size}")

reshape_column = matrix_4x3.reshape(1, -1)
print(f"Reshape Column: {reshape_column}")

transpose_matrix = matrix_4x3.T
print(f"Transpose Matrix: {transpose_matrix}")

flattened = matrix_4x3.flatten()
print(f"Flattened: {flattened}")

det_4x3 = np.linalg.det(matrix_4x3[:3, :3])
print(f"Determinant: {det_4x3}")

diagonal_4x3 = np.diagonal(matrix_4x3)
print(f"Diagonal: {diagonal_4x3}")

diagonal_4x3_above = np.diagonal(matrix_4x3)
print(f"Diagonal: {diagonal_4x3}")

diagonal_4x3_below = np.diagonal(matrix_4x3)
print(f"Diagonal: {diagonal_4x3}")

matrix_3x3_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_3x3_b = np.array([[9,8,7],[6,5,4],[3,2,1]])

matrix_sum = matrix_3x3_a + matrix_3x3_b
print(f"Matrix Sum: {matrix_sum}")

matrix_sub = matrix_3x3_b - matrix_3x3_a
print(f"Matrix Sub: {matrix_sub}")

matrix_mul = matrix_3x3_a * matrix_3x3_b
print(f"Matrix Mul: {matrix_mul}")



Mean: 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
Column Mean: [4. 5. 6.]
Size: 12
Reshape Column: [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
Transpose Matrix: [[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
Flattened: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Determinant: 0.0
Diagonal: [1 5 9]
Diagonal: [1 5 9]
Diagonal: [1 5 9]
Matrix Sum: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matrix Sub: [[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]
Matrix Mul: [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
