In [8]:
import numpy as np

row_vector = np.array([1, 2, 3])
print("Row Vector:" , row_vector)

column_vector = np.array([[1], [2], [3]])
print("Column Vector:\n" , column_vector)

#3 x 3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:\n" , matrix)

print("All elements of matrix:\n" , matrix)

print("Second row second column:\n" , matrix[1,1])

print("First two rows and all columns:\n" , matrix[:2, :])

print("All elements of last row:\n" , matrix[2, :])

print("All elements of last columns:\n" , matrix[: , 2])

Row Vector: [1 2 3]
Column Vector:
 [[1]
 [2]
 [3]]
Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
All elements of matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second row second column:
 5
First two rows and all columns:
 [[1 2 3]
 [4 5 6]]
All elements of last row:
 [7 8 9]
All elements of last columns:
 [3 6 9]
